### DISCUSSION TITLE
Trying to get a docker compose working but query service is not starting

### DISCUSSION THREAD

**Discussion by joestein-ssc** [databendlabs/databend#17541] [Q&A]
Here are my configs and docker compose and logs and error I am getting.

databend-meta.toml
```
[log]
level = "INFO"

[meta]
mode = "single"
raft_api_port = 9191
advertise_host = "databend-meta"  # This makes gRPC accessible as databend-meta:9191
```

databend-query-toml
```
[log]
level = "INFO"

[query]
tenant_id = "default"

[meta]
endpoints = ["databend-meta:9191"]

[storage]
type = "s3"

[storage.s3]
bucket = "databend-bucket"
endpoint_url = "http://minio:9000"
access_key_id = "minioadmin"
secret_access_key = "minioadmin"
region = "us-east-1"
```

docker-compose.yml
```
version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    networks:
      - databend_network      
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9090"
    volumes:
      - minio_data:/data

  databend-meta:
    hostname: databend-meta
    image: datafuselabs/databend-meta:latest
    container_name: databend-meta
    ports:
      - "9191:9191"
    networks:
      - databend_network      
    volumes:
      - ./databend-meta.toml:/databend-meta.toml  # Mount config file
      - ~/dev/apollo_data/databend_meta_data:/var/lib/databend-meta
    command: ["--single", "--config-file=/databend-meta.toml"]

  databend-query:
    image: datafuselabs/databend-query:latest
    container_name: databend-query
    depends_on:
      - databend-meta
      - minio
    ports:
      - "8000:8000"
      - "3307:3307"
    networks:
      - databend_network    
    restart: on-failure  
    volumes:
      - ./databend-query.toml:/databend-query.toml  # Mount config file
      - ~/dev/apollo_data/databend_query_data:/var/lib/databend-query
    command: ["databend-query", "--config-file=/databend-query.toml"]

networks:
  databend_network:
    driver: bridge

volumes:
  minio_data:
  databend_meta_data:
  databend_query_data:
```
logs with error
```
[+] Building 0.0s (0/0)                                                                                                                                                                                                    docker:desktop-linux
[+] Running 3/0
 ✔ Container databend-meta   Created                                                                                                                                                                                                       0.0s 
 ✔ Container minio           Created                                                                                                                                                                                                       0.0s 
 ✔ Container databend-query  Created                                                                                                                                                                                                       0.0s 
Attaching to databend-meta, databend-query, minio
databend-meta   | Databend Metasrv
databend-meta   | 
databend-meta   | Version: v1.2.697-d40f88cc51-simd(1.85.0-nightly-2025-02-14T11:38:22.118901603Z)
databend-meta   | Working DataVersion: V004(2024-11-11: WAL based raft-log)
databend-meta   | 
databend-meta   | Raft Feature set:
databend-meta   |     Server Provide: { append:v0, install_snapshot:v1, install_snapshot:v3, vote:v0 }
databend-meta   |     Client Require: { append:v0, install_snapshot:v3, vote:v0 }
databend-meta   | 
databend-meta   | Disk  Data: V004(2024-11-11: WAL based raft-log); Upgrading: None
databend-meta   |       Dir: ./.databend/meta
databend-meta   | 
databend-meta   | Log   File:   enabled=true, level='Warn,databend_=Info,openraft=Info', dir=./.databend/logs, format=json, limit=48
databend-meta   |       Stderr: enabled=false(To enable: LOG_STDERR_ON=true or RUST_LOG=info), level=Warn,databend_=Info,openraft=Info, format=text
databend-meta   | Raft  Id: 0; Cluster: foo_cluster
databend-meta   |       Dir: ./.databend/meta
databend-meta   |       Status: single
databend-meta   | 
databend-meta   | HTTP API listen at: 127.0.0.1:28002
databend-meta   | gRPC API listen at: 127.0.0.1:9191 advertise: -
databend-meta   | Raft API listen at: 127.0.0.1:28004 advertise: databend-meta:28004
databend-meta   | 
databend-meta   | Upgrade ondisk data if out of date: V004
databend-meta   |     Find and clean previous unfinished upgrading
databend-meta   | Upgrade ondisk data finished: V004
databend-meta   | Wait for 180s for active leader...
databend-meta   | Leader Id: 0
databend-meta   |     Metrics: id=0, Leader, term=1, last_log=Some(6), last_applied=Some(T1-N0.6), membership={log_id:Some(T1-N0.3), {voters:[{0:EmptyNode}], learners:[]}}
databend-meta   | 
databend-meta   | Register this node: {id=0 raft=databend-meta:28004 grpc=}
databend-meta   | 
databend-meta   |     Register-node: Ok
databend-meta   | 
databend-meta   | Databend Metasrv started
minio           | MinIO Object Storage Server
minio           | Copyright: 2015-2025 MinIO, Inc.
minio           | License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
minio           | Version: RELEASE.2025-02-28T09-55-16Z (go1.23.6 linux/arm64)
minio           | 
minio           | API: http://172.24.0.2:9000  http://127.0.0.1:9000 
minio           | WebUI: http://172.24.0.2:9090 http://127.0.0.1:9090 
minio           | 
minio           | Docs: https://docs.min.io
minio           | WARN: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
databend-query  | Databend Query start failure, cause: MetaServiceError. Code: 2001, Text = ConnectionError: while creating rpc channel source: databend_common_grpc::dns_resolver::GrpcConnectionError: can not connect to http://databend-meta:9191/, error: tonic::transport::error::Error: transport error; source: tcp connect error: Connection refused (os error 111); source: tcp connect error: Connection refused (os error 111); source: Connection refused (os error 111); source: tonic::transport::error::Error: transport error; source: tcp connect error: Connection refused (os error 111); source: tcp connect error: Connection refused (os error 111); source: Connection refused (os error 111).
databend-query  | 
databend-query  | <Backtrace disabled by default. Please use RUST_BACKTRACE=1 to enable> 
databend-query exited with code 0
databend-query  | Databend Query start failure, cause: MetaServiceError. Code: 2001, Text = ConnectionError: while creating rpc channel source: databend_common_grpc::dns_resolver::GrpcConnectionError: can not connect to http://databend-meta:9191/, error: tonic::transport::error::Error: transport error; source: tcp connect error: Connection refused (os error 111); source: tcp connect error: Connection refused (os error 111); source: Connection refused (os error 111); source: tonic::transport::error::Error: transport error; source: tcp connect error: Connection refused (os error 111); source: tcp connect error: Connection refused (os error 111); source: Connection refused (os error 111).
databend-query  | 
databend-query  | <Backtrace disabled by default. Please use RUST_BACKTRACE=1 to enable> 
databend-query exited with code 0
```

Any help with why the query server can't connect to the gRPC meta service please? It seems weird that is has http for the grpc not sure that is related but I do not have that in my configs.

Thanks!

Joe Stein
