### DISCUSSION TITLE
proposal: Refactor CI pipleline into stages

### DISCUSSION THREAD

**Discussion by Xuanwo** [databendlabs/databend#3415] [Ideas]
Hello, everyone!

CI is an important part of our community. Every contributor will meet them in every PR. Databend's CI didn't well organize in the past. In this proposal, I will discuss a new design of CI with the whole community.

## Goal

- Fast: run needed CI only.
- Easy: easy to understand, easy to maintain.

## How it works?

Github allows us to:

- Share artifacts between jobs in the same workflow.
- Reuse actions in different workflows/jobs.

So, instead of splitting jobs into different workflows, we can have a `main.yml` that organizes all related jobs together. In the case of databend, we will have two profiles:

- `developing.yml`: Used in all PRs and non-main branches
- `production.yml`: Used in main branch, build with `--release` and publish images.

Let's take a look at `developing.yml` for glance:

```yml
name: Developing

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/check

  build:
    runs-on: ${{ matrix.config.os }}
    needs: check
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu, cross: false }
          - { os: ubuntu-latest, target: aarch64-unknown-linux-gnu, cross: true }
          - { os: macos-11, target: x86_64-apple-darwin, cross: false }
          - { os: macos-11, target: aarch64-apple-darwin, cross: false }
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build_debug

  test_unit:
    runs-on: ${{ matrix.config.os }}
    needs: build
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
          - { os: macos-11, target: x86_64-apple-darwin }
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test_unit
      
  test_stateless_standalone:
    runs-on: ${{ matrix.config.os }}
    needs: build
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
          - { os: macos-11, target: x86_64-apple-darwin }
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test_stateless_standalone

  test_stateless_cluster:
    runs-on: ${{ matrix.config.os }}
    needs: build
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
          - { os: macos-11, target: x86_64-apple-darwin }
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test_stateless_cluster

  test_stateful_standalone:
    runs-on: ${{ matrix.config.os }}
    needs: build
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test_stateful_standalone
```

In this way, we don't need to guess which workflow could be run. And we can have a global view of our jobs like:

![image](https://user-images.githubusercontent.com/5351546/145757876-2904fd1f-8982-4c53-87e5-73d2a8e23fbc.png)

## Benefits

- With the `needs` support, we can only allow running `build` after `check` passed.
- We can share the artifacts that were built at `build` steps in `tests` so that we don't need to build them again.
- We can remove duplicated `concurrency` and `paths-ignore` in different workflows.

## Demo

Here is a working demo: https://github.com/datafuselabs/databend/pull/3344

Welcome for any comments and reviews!

## Tracking issues

https://github.com/datafuselabs/databend/issues/3453
