### ISSUE TITLE
Improve meta-service config usability 

### ISSUE THREAD

**Issue by drmingdrmer** [databendlabs/databend#14541]
Currently, the first meta-service node in a cluster must be configured with `single`, and others are configured with `join`:

```toml
# node-1
[raft_config]
id = 1
single        = true

# node-2
[raft_config]
id            = 2
join          = ["127.0.0.1:9001"]
```

This `single`/`join` mechanism introduces complexity setting up a cluster.
It is possible to specify the cluster configure with one same config for every node:

```toml
# node-1
[raft_config]
id = 1
cluster = ["127.0.0.1:9001", "127.0.0.1:9002"]

# node-2
[raft_config]
id            = 2
cluster = ["127.0.0.1:9001", "127.0.0.1:9002"]
```
